### ISSUE TITLE
Questions on the roadmap

### ISSUE THREAD

**Issue by krak3n77** [Ferrazzi/FlipperZero_IFTTT_Virtual_Button#1]
I've tried porting to the esp32s2 flipper dev board. Haven't really gotten it to work. I got my esp32s2 to connect to wifi, but it it won't send an ifttt webhook.
Is there any plans on making a esp32s2 version?

**Comment by Ferrazzi** [comment]
hello I'll try to bring the ESP code also for the devboard

**Comment by krak3n77** [comment]
Sounds great! 👍
